config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :songs do
  	resources :user_songs, only:[:create]
  end

  resources :users, only: [:index, :show] do
  	resources :user_songs, only:[:destroy]
  end
  resources :genres
  root 'songs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="/"> <%= image_tag('spotifylogo', :size => "70x70") %></a>
      <span><a href="<%= songs_path %>" style= 'font-family: Lato Black'> MINI SPOTIFY /</a></span>
      <span><a href="<%= users_path %>"> Users /</a></span>
      <span><a href="<%= genres_path %>">Genres /</a></span>
      <span><a href="<%= songs_path %>">Songs </a></span>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <% if user_signed_in? %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= current_user.name.blank? ? 'Usuario' : current_user.name %>
          </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to "Salir",
            destroy_user_session_path,
              method: 'delete'
              %>
            </li>
          </ul>
          <% else %>
          <li><a href="<%= new_user_session_path %>"> Login </a></li>
          <li><a href="<%= new_user_registration_path %>"> Registro </a></li>
          <% end %>
        </ul>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Spotify test /Javiera Tapia</title>
	<%= csrf_meta_tags %>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>

<body>
	<%= render 'layouts/navbar' %>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	
	<%= yield %>
</body>
</html>